#!/usr/bin/env bash
#
# Score docling.rs's chunkers against docling-core's HierarchicalChunker and
# HybridChunker over the chunking corpus.
#
# Groundtruth (tests/data/chunks/groundtruth/*.json) is generated by
# scripts/conformance/gen_chunks.py with live Python docling. This script runs
# `docling-rs --to chunks` on every corpus source and compares the chunk
# records' (text, headings, contextualize) — the payload a RAG pipeline embeds.
# Internal item refs are structural (docling splits inline content into more
# items than docling.rs) and are not part of the score.
#
# Usage: scripts/conformance/chunks_conformance.sh [source-glob ...]

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../.."
cd "$REPO"

export DOCLING_CHUNK_TOKENIZER="$REPO/tests/data/chunks/tokenizer.json"

cargo build --quiet --release -p docling-cli --features chunking
BIN=target/release/docling-rs

GT_DIR=tests/data/chunks/groundtruth

python3 - "$@" <<'EOF'
import json, os, subprocess, sys
from pathlib import Path

REPO = Path.cwd()
GT_DIR = REPO / "tests/data/chunks/groundtruth"
BIN = REPO / "target/release/docling-rs"

def source_for(stem: str) -> Path | None:
    # stem is the source file name; its extension picks the corpus dir
    ext = stem.rsplit(".", 1)[-1]
    fmt = {"html": "html", "docx": "docx", "md": "md", "xlsx": "xlsx", "pptx": "pptx"}.get(ext)
    if not fmt:
        return None
    p = REPO / "tests/data" / fmt / "sources" / stem
    return p if p.exists() else None

def records(chunks):
    return [(c["text"], tuple(c["headings"] or []), c["contextualize"]) for c in chunks]

names = sorted({f.name.rsplit(".", 2)[0] for f in GT_DIR.glob("*.json")})
if len(sys.argv) > 1:
    names = [n for n in names if any(a in n for a in sys.argv[1:])]

total = {"hierarchical": 0, "hybrid": 0}
exact = {"hierarchical": 0, "hybrid": 0}
chunks_total = {"hierarchical": 0, "hybrid": 0}
chunks_match = {"hierarchical": 0, "hybrid": 0}

print(f"{'source':46} {'hierarchical':>14} {'hybrid':>14}")
for name in names:
    src = source_for(name)
    if src is None:
        continue
    out = subprocess.run([BIN, "--to", "chunks", str(src)], capture_output=True, text=True)
    if out.returncode != 0:
        print(f"{name:46} {'CONVERT FAIL':>14}")
        continue
    ours = json.loads(out.stdout)
    row = [f"{name:46}"]
    for chunker in ("hierarchical", "hybrid"):
        gt = records(json.loads((GT_DIR / f"{name}.{chunker}.json").read_text()))
        got = records(ours.get(chunker, []))
        total[chunker] += 1
        # per-chunk positional match count
        m = sum(1 for a, b in zip(gt, got) if a == b)
        chunks_total[chunker] += len(gt)
        chunks_match[chunker] += m
        if gt == got:
            exact[chunker] += 1
            row.append(f"{'ok':>14}")
        else:
            row.append(f"{f'{m}/{len(gt)}':>14}")
    print(" ".join(row))

print()
for chunker in ("hierarchical", "hybrid"):
    pct = 100.0 * chunks_match[chunker] / max(chunks_total[chunker], 1)
    print(
        f"{chunker:14} exact docs: {exact[chunker]:3} / {total[chunker]:3}   "
        f"chunk records: {chunks_match[chunker]} / {chunks_total[chunker]} ({pct:.1f}%)"
    )
EOF
