#!/usr/bin/env bash
# Score docling.rs's `--to dclx` output against the Python-docling groundtruth
# archives (tests/data/<fmt>/groundtruth_dclx/*.dclx, generated by
# scripts/conformance/gen_dclx.py). Comparison is the extracted document.xml, line-diffed;
# zip metadata and image payloads are ignored by design (timestamps and PNG
# encoders differ legitimately).
#
#   scripts/conformance/dclx_conformance.sh [fmt ...]     # default: all formats with groundtruth
#
# Prints per-fixture EXACT / diff-line counts and a summary split into the
# issue #32 targets: >=90% similarity for non-PDF formats, >=50% for PDF.
# "Similarity" per fixture = 100 * (1 - difflines / max(lines_ref, lines_ours)).
set -uo pipefail
cd "$(dirname "$0")/../.."

BIN="$(pwd)/target/release/docling-rs"
[ -x "$BIN" ] || { echo "build first: cargo build --release -p docling-cli" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

declare -a fmts=()
if [ $# -gt 0 ]; then fmts=("$@"); else
  for d in tests/data/*/groundtruth_dclx; do [ -d "$d" ] && fmts+=("$(basename "$(dirname "$d")")"); done
fi

pdf_sum=0; pdf_n=0; other_sum=0; other_n=0
printf "%-52s %10s %8s\n" FIXTURE DIFF-LINES SIM%
for fmt in "${fmts[@]}"; do
  gdir=tests/data/$fmt/groundtruth_dclx
  [ -d "$gdir" ] || continue
  case "$fmt" in pdf|scanned|tiff|webp|pdf_password) is_pdf=1 ;; *) is_pdf=0 ;; esac
  for ref in "$gdir"/*.dclx; do
    base=$(basename "$ref" .dclx)          # e.g. wiki.md
    src=tests/data/$fmt/sources/$base
    [ -f "$src" ] || continue
    (cd "$tmp" && "$BIN" --to dclx "$OLDPWD/$src" >/dev/null 2>&1)
    ours=$tmp/"${base%.*}".dclx
    if [ ! -f "$ours" ]; then
      printf "%-52s %10s %8s\n" "$fmt/$base" "FAIL" "0"
      sim=0
    else
      unzip -p "$ref" document.xml > "$tmp/ref.xml" 2>/dev/null
      unzip -p "$ours" document.xml > "$tmp/ours.xml" 2>/dev/null
      d=$(diff "$tmp/ref.xml" "$tmp/ours.xml" | grep -c '^[<>]')
      lr=$(wc -l < "$tmp/ref.xml"); lo=$(wc -l < "$tmp/ours.xml")
      max=$(( lr > lo ? lr : lo )); [ "$max" -eq 0 ] && max=1
      sim=$(( 100 * (max*2 - d) / (max*2) ))   # d counts both sides
      [ "$sim" -lt 0 ] && sim=0
      if [ "$d" -eq 0 ]; then
        printf "%-52s %10s %8s\n" "$fmt/$base" "EXACT" "100"
      else
        printf "%-52s %10s %8s\n" "$fmt/$base" "$d" "$sim"
      fi
      rm -f "$ours"
    fi
    if [ "$is_pdf" -eq 1 ]; then pdf_sum=$((pdf_sum+sim)); pdf_n=$((pdf_n+1));
    else other_sum=$((other_sum+sim)); other_n=$((other_n+1)); fi
  done
done
echo "----"
[ "$other_n" -gt 0 ] && echo "non-PDF avg similarity: $((other_sum/other_n))%  (target 90%) over $other_n fixtures"
[ "$pdf_n" -gt 0 ] && echo "PDF avg similarity:     $((pdf_sum/pdf_n))%  (target 50%) over $pdf_n fixtures"
