#!/usr/bin/env bash
# Score docling.rs's `--to dclx` output against the Python-docling groundtruth
# archives (tests/data/<fmt>/groundtruth_dclx/*.dclx, generated by
# scripts/conformance/gen_dclx.py). Comparison is the extracted document.xml, line-diffed;
# zip metadata and image payloads are ignored by design (timestamps and PNG
# encoders differ legitimately).
#
#   scripts/conformance/dclx_conformance.sh [fmt ...]     # default: all formats with groundtruth
#
# Prints per-fixture EXACT / diff-line counts and a summary split into the
# issue #32 targets: >=90% similarity for non-PDF formats, >=50% for PDF.
# "Similarity" per fixture = 100 * (1 - difflines / max(lines_ref, lines_ours)).
#
# PDF geometry tolerance (DCLX_TOL, default 2 grid units): on the PDF path the
# reference `<location>` provenance (l,t,r,b on docling's 0-500 normalized page
# grid) comes from docling's layout clusters while ours come from our own layout
# post-processing, so the same region is boxed a few grid units apart.
# dclx_diff.py counts a location pair as matching when the two values are within
# DCLX_TOL; text, structure, and every non-geometry line stay byte-exact, and
# unmatched lines always count. The tolerance is applied ONLY to PDF fixtures --
# formats whose geometry is read from the same source file (OOXML slides/sheets)
# are still compared exactly (tol=0).
set -uo pipefail
cd "$(dirname "$0")/../.."
TOL="${DCLX_TOL:-2}"
DIFF="$(dirname "$0")/dclx_diff.py"

BIN="$(pwd)/target/release/docling-rs"
[ -x "$BIN" ] || { echo "build first: cargo build --release -p docling-cli" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# The binary resolves models/.pdfium relative to its CWD (then next to the exe);
# we run it inside $tmp so the .dclx lands there, so make the assets reachable
# from $tmp. Harmless for declarative formats that load no models.
export PDFIUM_DYNAMIC_LIB_PATH="$(pwd)/.pdfium/lib"
[ -d models ]  && ln -sfn "$(pwd)/models"  "$tmp/models"
[ -d .pdfium ] && ln -sfn "$(pwd)/.pdfium" "$tmp/.pdfium"

declare -a fmts=()
if [ $# -gt 0 ]; then fmts=("$@"); else
  for d in tests/data/*/groundtruth_dclx; do [ -d "$d" ] && fmts+=("$(basename "$(dirname "$d")")"); done
fi

pdf_sum=0; pdf_n=0; other_sum=0; other_n=0
printf "%-52s %10s %8s\n" FIXTURE DIFF-LINES SIM%
for fmt in "${fmts[@]}"; do
  gdir=tests/data/$fmt/groundtruth_dclx
  [ -d "$gdir" ] || continue
  case "$fmt" in pdf|scanned|tiff|webp|pdf_password) is_pdf=1 ;; *) is_pdf=0 ;; esac
  for ref in "$gdir"/*.dclx; do
    base=$(basename "$ref" .dclx)          # e.g. wiki.md
    src=tests/data/$fmt/sources/$base
    [ -f "$src" ] || continue
    (cd "$tmp" && "$BIN" --to dclx "$OLDPWD/$src" >/dev/null 2>&1)
    ours=$tmp/"${base%.*}".dclx
    if [ ! -f "$ours" ]; then
      printf "%-52s %10s %8s\n" "$fmt/$base" "FAIL" "0"
      sim=0
    else
      unzip -p "$ref" document.xml > "$tmp/ref.xml" 2>/dev/null
      unzip -p "$ours" document.xml > "$tmp/ours.xml" 2>/dev/null
      # Canonicalize exported image asset names. docling names referenced images
      # assets/image_NNNNNN_<sha256>.png, where the digest is over the PIL-re-encoded
      # PNG bytes — not reproducible outside docling. We emit the same structure with
      # a source-bytes hash, so the index+digest are normalized on both sides here;
      # only a genuine structural difference (missing/extra <src>) then shows up.
      sed -E -i 's#image_[0-9]{6}_[0-9a-f]+\.png#image_NORM.png#g' \
        "$tmp/ref.xml" "$tmp/ours.xml"
      ftol=0; [ "$is_pdf" -eq 1 ] && ftol="$TOL"   # geometry tolerance: PDF only
      d=$(python3 "$DIFF" "$tmp/ref.xml" "$tmp/ours.xml" --tol "$ftol")
      lr=$(wc -l < "$tmp/ref.xml"); lo=$(wc -l < "$tmp/ours.xml")
      max=$(( lr > lo ? lr : lo )); [ "$max" -eq 0 ] && max=1
      sim=$(( 100 * (max*2 - d) / (max*2) ))   # d counts both sides
      [ "$sim" -lt 0 ] && sim=0
      if [ "$d" -eq 0 ]; then
        printf "%-52s %10s %8s\n" "$fmt/$base" "EXACT" "100"
      else
        printf "%-52s %10s %8s\n" "$fmt/$base" "$d" "$sim"
      fi
      rm -f "$ours"
    fi
    if [ "$is_pdf" -eq 1 ]; then pdf_sum=$((pdf_sum+sim)); pdf_n=$((pdf_n+1));
    else other_sum=$((other_sum+sim)); other_n=$((other_n+1)); fi
  done
done
echo "----"
[ "$other_n" -gt 0 ] && echo "non-PDF avg similarity: $((other_sum/other_n))%  (target 90%, exact geometry) over $other_n fixtures"
[ "$pdf_n" -gt 0 ] && echo "PDF avg similarity:     $((pdf_sum/pdf_n))%  (target 50%, +/-${TOL} grid-unit geometry tolerance) over $pdf_n fixtures"
