#!/usr/bin/env bash
#
# Score fleischwolf's Markdown output against Python docling across a corpus.
#
# Two reference sources:
#   (default)  the committed groundtruth under tests/data/<fmt>/groundtruth/*.md
#              — fast, needs no Python, but can be STALE relative to the current
#              docling-core serializer (notably table formatting).
#   --live     freshly generated by running the local Python docling on each
#              source — the true "do we match current docling?" number.
#              Sets up the local docling install on first use (see _common.sh).
#
# Usage:
#   scripts/conformance.sh [format] [--live]
#   scripts/conformance.sh html
#   scripts/conformance.sh html --live
#
# Output: a per-file table (diff-line count; one changed line counts as 2) and a
# summary.

set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"

FORMAT="html"
LIVE=0
for arg in "$@"; do
  case "$arg" in
    --live) LIVE=1 ;;
    *) FORMAT="$arg" ;;
  esac
done

DATA_DIR="$CORPUS_DIR/$FORMAT"
SRC_DIR="$DATA_DIR/sources"
GT_DIR="$DATA_DIR/groundtruth"

if [[ ! -d "$SRC_DIR" ]]; then
  echo "error: corpus not found under $DATA_DIR" >&2
  exit 1
fi

if [[ "$LIVE" -eq 1 ]]; then
  ensure_docling
  echo ">> reference: LIVE python docling"
else
  echo ">> reference: committed groundtruth (may be stale; use --live for current)"
fi

# Build once up front so per-file timing isn't dominated by compilation.
cargo build --quiet --manifest-path "$MANIFEST" -p fleischwolf-cli

# Write the reference Markdown for a source into $1; returns non-zero to skip.
# Groundtruth is named "<source>.md" for most formats but "<stem>.md" for PDF
# (e.g. 2305.03393v1-pg9.md). For --live we run the installed Python docling; if
# it can't produce output for a source we fall back to the committed groundtruth.
reference_into() {
  local src="$1" out="$2" base stem cand
  base="$(basename "$src")"
  stem="${base%.*}"
  if [[ "$LIVE" -eq 1 ]]; then
    if "$PYBIN" "$PY_RUNNER" "$src" "$out" 2>/dev/null && [[ -s "$out" ]]; then
      return 0
    fi
  fi
  for cand in "$GT_DIR/$base.md" "$GT_DIR/$stem.md"; do
    [[ -f "$cand" ]] && { cp "$cand" "$out"; return 0; }
  done
  return 1
}

printf "%-44s %12s\n" "FIXTURE" "DIFF-LINES"
printf "%-44s %12s\n" "-------" "----------"

total=0
exact=0
close=0
ref="$(mktemp)"
trap 'rm -f "$ref"' EXIT
for src in "$SRC_DIR"/*; do
  reference_into "$src" "$ref" || continue
  total=$((total + 1))

  out="$(cargo run --quiet --manifest-path "$MANIFEST" -p fleischwolf-cli -- "$src" 2>/dev/null || echo '<ERROR>')"
  # Compare trailing-newline-insensitively.
  d="$(diff <(printf '%s' "$out") <(printf '%s' "$(cat "$ref")") | grep -cE '^[<>]' || true)"

  if [[ "$d" -eq 0 ]]; then
    exact=$((exact + 1))
    mark="EXACT"
  else
    [[ "$d" -le 2 ]] && close=$((close + 1))
    mark="$d"
  fi
  printf "%-44s %12s\n" "$(basename "$src")" "$mark"
done

echo
echo "Exact matches:             $exact / $total"
echo "Exact or 1-line-different: $((exact + close)) / $total"
